name: Deploy to GitHub Pages
permissions:
  contents: write

on:
  push:
    branches:
      - master
      - feat/setup-blog-deploy

jobs:
  build_and_deploy:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
    - name: Install Zola
      run: |
        # Download the Zola binary
        curl -sL https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz | tar xz
        # Move the binary to a directory in PATH
        sudo mv zola /usr/local/bin/
        # Verify installation
        zola --version
    - name: Build site
      run: zola build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
